POST http://localhost:20004/foundation/generate/template/group
Content-Type: application/json

{
  "groupName": "后端",
  "parentId": 0,
  "parentList": "0",
  "order": 0,
  "type": 0,
  "userId": 1,
  "createBy": 1
}
